### ISSUE TITLE
Gdzie link do Figmy?

### ISSUE THREAD

**Issue by rafal11ck** [kurczakooo/React-Native-Project#1]

**Comment by filip-stepien** [comment]
jest jako plik w repo ale wsm robienie tego na jednym wspólnym projekcie to nie głupi pomysł bo chyba będzie widać że ktoś coś edytuje w danym momencie

jak dacie nicki to dodam was do projektu

@kurczakooo
@rafal11ck

**Comment by rafal11ck** [comment]
Taki sam jak tu.

**Comment by filip-stepien** [comment]
dodam ale i tak będę wrzucał plik do repo na wszelki
